version: 2.1
commands:
  # TODO: Is there a better way to do this? My first instinct is to create a specialized docker
  # image with my preferred version of Node and PNPM and then persist deps, but I'm not sure if
  # that's the best move. All I know is that this is slow as fuck
  setup-deps:
    steps:
      - checkout
      - restore_cache:
          name: Restore PNPM Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install PNPM
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies and Check Package Versions
          command: |
            pnpm install
jobs:
  setup:
    docker:
      - image: node:20
    steps:
      - setup-deps
      - run:
          name: Build All Packages
          command: |
            pnpm run build:packages
      - persist_to_workspace:
          root: .
          paths:
            - 'packages/ui/dist'
      - save_cache:
          name: Save PNPM Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
  build-apps-and-servers:
    docker:
      - image: node:20
    # Prisma requires that a dv env var be set, so we're giving it a fake one
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/home-management?schema=public'
    steps:
      - setup-deps
      - attach_workspace:
          at: .
      - run:
          name: Build Apps and Servers
          command: |
            pnpm run build
  lint:
    docker:
      - image: node:20
    # Prisma requires that a dv env var be set, so we're giving it a fake one
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/home-management?schema=public'
    steps:
      - setup-deps
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            pnpm run lint
  lint-styles:
    docker:
      - image: node:20
    steps:
      - setup-deps
      - attach_workspace:
          at: .
      - run:
          name: Lint Styles
          command: |
            pnpm run styles:lint
  storybook-build:
    docker:
      - image: node:20
    steps:
      - setup-deps
      - attach_workspace:
          at: .
      - run:
          name: Build Storybook
          command: |
            pnpm --filter @jrkienle/ui run storybook:build
  test:
    docker:
      - image: node:20
    # Prisma requires that a dv env var be set, so we're giving it a fake one
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/home-management?schema=public'
    steps:
      - setup-deps
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            pnpm run test
workflows:
  build-test-deploy:
    jobs:
      - setup
      - build-apps-and-servers:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - lint-styles:
          requires:
            - setup
      - test:
          requires:
            - setup
